/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module study_top(clk, rst, data_in, data_out);
  wire [37:0] _000_;
  wire [36:0] _001_;
  wire [36:0] _002_;
  wire [36:0] _003_;
  wire [36:0] _004_;
  wire [36:0] _005_;
  wire [36:0] _006_;
  wire [15:0] \buf1[0] ;
  wire [15:0] \buf1[1] ;
  wire [15:0] \buf1[2] ;
  wire [15:0] \buf1[3] ;
  wire [15:0] \buf1[4] ;
  wire [15:0] \buf1[5] ;
  wire [15:0] \buf1[6] ;
  wire [15:0] \buf2[0] ;
  wire [15:0] \buf2[1] ;
  wire [15:0] \buf2[2] ;
  wire [15:0] \buf2[3] ;
  wire [15:0] \buf2[4] ;
  wire [15:0] \buf2[5] ;
  wire [15:0] \buf2[6] ;
  wire [15:0] \buf3[0] ;
  wire [15:0] \buf3[1] ;
  wire [15:0] \buf3[2] ;
  wire [15:0] \buf3[3] ;
  wire [15:0] \buf3[4] ;
  wire [15:0] \buf3[5] ;
  wire [15:0] \buf3[6] ;
  wire [15:0] \buf4[0] ;
  wire [15:0] \buf4[10] ;
  wire [15:0] \buf4[1] ;
  wire [15:0] \buf4[2] ;
  wire [15:0] \buf4[3] ;
  wire [15:0] \buf4[4] ;
  wire [15:0] \buf4[5] ;
  wire [15:0] \buf4[6] ;
  wire [15:0] \buf4[7] ;
  wire [15:0] \buf4[8] ;
  wire [15:0] \buf4[9] ;
  wire [15:0] \buf5[0] ;
  wire [15:0] \buf5[10] ;
  wire [15:0] \buf5[11] ;
  wire [15:0] \buf5[12] ;
  wire [15:0] \buf5[13] ;
  wire [15:0] \buf5[14] ;
  wire [15:0] \buf5[15] ;
  wire [15:0] \buf5[16] ;
  wire [15:0] \buf5[17] ;
  wire [15:0] \buf5[18] ;
  wire [15:0] \buf5[19] ;
  wire [15:0] \buf5[1] ;
  wire [15:0] \buf5[20] ;
  wire [15:0] \buf5[21] ;
  wire [15:0] \buf5[22] ;
  wire [15:0] \buf5[23] ;
  wire [15:0] \buf5[2] ;
  wire [15:0] \buf5[3] ;
  wire [15:0] \buf5[4] ;
  wire [15:0] \buf5[5] ;
  wire [15:0] \buf5[6] ;
  wire [15:0] \buf5[7] ;
  wire [15:0] \buf5[8] ;
  wire [15:0] \buf5[9] ;
  input clk;
  input [15:0] data_in;
  output [15:0] data_out;
  reg [15:0] data_out;
  input rst;
  reg [15:0] \s1.buf_0 ;
  reg [15:0] \s1.buf_1 ;
  reg [15:0] \s1.buf_2 ;
  reg [15:0] \s1.buf_3 ;
  reg [15:0] \s1.buf_4 ;
  reg [15:0] \s1.buf_5 ;
  reg [15:0] \s1.buf_6 ;
  wire [15:0] \s1.out ;
  wire [35:0] \s1.p0 ;
  wire [35:0] \s1.p1 ;
  wire [35:0] \s1.p2 ;
  wire [35:0] \s1.p3 ;
  wire [16:0] \s1.s0 ;
  wire [16:0] \s1.s1 ;
  wire [16:0] \s1.s2 ;
  wire [36:0] \s1.sum_1 ;
  wire [36:0] \s1.sum_2 ;
  wire [36:0] \s1.sum_3 ;
  reg [15:0] \s2.buf_0 ;
  reg [15:0] \s2.buf_1 ;
  reg [15:0] \s2.buf_2 ;
  reg [15:0] \s2.buf_3 ;
  reg [15:0] \s2.buf_4 ;
  reg [15:0] \s2.buf_5 ;
  reg [15:0] \s2.buf_6 ;
  wire [15:0] \s2.out ;
  wire [35:0] \s2.p0 ;
  wire [35:0] \s2.p1 ;
  wire [35:0] \s2.p2 ;
  wire [35:0] \s2.p3 ;
  wire [16:0] \s2.s0 ;
  wire [16:0] \s2.s1 ;
  wire [16:0] \s2.s2 ;
  wire [36:0] \s2.sum_1 ;
  wire [36:0] \s2.sum_2 ;
  wire [36:0] \s2.sum_3 ;
  reg [15:0] \s3.buf_0 ;
  reg [15:0] \s3.buf_1 ;
  reg [15:0] \s3.buf_2 ;
  reg [15:0] \s3.buf_3 ;
  reg [15:0] \s3.buf_4 ;
  reg [15:0] \s3.buf_5 ;
  reg [15:0] \s3.buf_6 ;
  wire [15:0] \s3.out ;
  wire [35:0] \s3.p0 ;
  wire [35:0] \s3.p1 ;
  wire [35:0] \s3.p2 ;
  wire [35:0] \s3.p3 ;
  wire [16:0] \s3.s0 ;
  wire [16:0] \s3.s1 ;
  wire [16:0] \s3.s2 ;
  wire [36:0] \s3.sum_1 ;
  wire [36:0] \s3.sum_2 ;
  wire [36:0] \s3.sum_3 ;
  reg [15:0] \s4.buf_0 ;
  reg [15:0] \s4.buf_1 ;
  reg [15:0] \s4.buf_10 ;
  reg [15:0] \s4.buf_2 ;
  reg [15:0] \s4.buf_3 ;
  reg [15:0] \s4.buf_4 ;
  reg [15:0] \s4.buf_5 ;
  reg [15:0] \s4.buf_6 ;
  reg [15:0] \s4.buf_7 ;
  reg [15:0] \s4.buf_8 ;
  reg [15:0] \s4.buf_9 ;
  wire [15:0] \s4.out ;
  wire [35:0] \s4.p0 ;
  wire [35:0] \s4.p1 ;
  wire [35:0] \s4.p2 ;
  wire [35:0] \s4.p3 ;
  wire [35:0] \s4.p4 ;
  wire [35:0] \s4.p5 ;
  wire [16:0] \s4.s0 ;
  wire [16:0] \s4.s1 ;
  wire [16:0] \s4.s2 ;
  wire [16:0] \s4.s3 ;
  wire [16:0] \s4.s4 ;
  wire [36:0] \s4.sum_1 ;
  wire [36:0] \s4.sum_2 ;
  wire [36:0] \s4.sum_3 ;
  wire [36:0] \s4.sum_4 ;
  wire [36:0] \s4.sum_5 ;
  wire [15:0] \s5.buf_0 ;
  wire [15:0] \s5.buf_1 ;
  wire [15:0] \s5.buf_10 ;
  wire [15:0] \s5.buf_11 ;
  reg [15:0] \s5.buf_12 ;
  wire [15:0] \s5.buf_13 ;
  wire [15:0] \s5.buf_14 ;
  wire [15:0] \s5.buf_15 ;
  wire [15:0] \s5.buf_16 ;
  wire [15:0] \s5.buf_17 ;
  wire [15:0] \s5.buf_18 ;
  wire [15:0] \s5.buf_19 ;
  wire [15:0] \s5.buf_2 ;
  wire [15:0] \s5.buf_20 ;
  wire [15:0] \s5.buf_21 ;
  wire [15:0] \s5.buf_22 ;
  wire [15:0] \s5.buf_23 ;
  wire [15:0] \s5.buf_3 ;
  wire [15:0] \s5.buf_4 ;
  wire [15:0] \s5.buf_5 ;
  wire [15:0] \s5.buf_6 ;
  wire [15:0] \s5.buf_7 ;
  wire [15:0] \s5.buf_8 ;
  wire [15:0] \s5.buf_9 ;
  wire [15:0] \s5.out ;
  wire [36:0] \s5.partial0 ;
  wire [36:0] \s5.partial1 ;
  wire [36:0] \s5.partial2 ;
  reg [15:0] \s5.s5_p0.buf_0 ;
  reg [15:0] \s5.s5_p0.buf_1 ;
  reg [15:0] \s5.s5_p0.buf_2 ;
  reg [15:0] \s5.s5_p0.buf_20 ;
  reg [15:0] \s5.s5_p0.buf_21 ;
  reg [15:0] \s5.s5_p0.buf_22 ;
  reg [15:0] \s5.s5_p0.buf_23 ;
  reg [15:0] \s5.s5_p0.buf_3 ;
  wire [35:0] \s5.s5_p0.p0 ;
  wire [35:0] \s5.s5_p0.p1 ;
  wire [35:0] \s5.s5_p0.p2 ;
  wire [35:0] \s5.s5_p0.p3 ;
  wire [36:0] \s5.s5_p0.partial0 ;
  wire [16:0] \s5.s5_p0.s0 ;
  wire [16:0] \s5.s5_p0.s1 ;
  wire [16:0] \s5.s5_p0.s2 ;
  wire [16:0] \s5.s5_p0.s3 ;
  reg [15:0] \s5.s5_p1.buf_16 ;
  reg [15:0] \s5.s5_p1.buf_17 ;
  reg [15:0] \s5.s5_p1.buf_18 ;
  reg [15:0] \s5.s5_p1.buf_19 ;
  reg [15:0] \s5.s5_p1.buf_4 ;
  reg [15:0] \s5.s5_p1.buf_5 ;
  reg [15:0] \s5.s5_p1.buf_6 ;
  reg [15:0] \s5.s5_p1.buf_7 ;
  wire [35:0] \s5.s5_p1.p4 ;
  wire [35:0] \s5.s5_p1.p5 ;
  wire [35:0] \s5.s5_p1.p6 ;
  wire [35:0] \s5.s5_p1.p7 ;
  wire [36:0] \s5.s5_p1.partial1 ;
  wire [16:0] \s5.s5_p1.s4 ;
  wire [16:0] \s5.s5_p1.s5 ;
  wire [16:0] \s5.s5_p1.s6 ;
  wire [16:0] \s5.s5_p1.s7 ;
  reg [15:0] \s5.s5_p2.buf_10 ;
  reg [15:0] \s5.s5_p2.buf_11 ;
  reg [15:0] \s5.s5_p2.buf_13 ;
  reg [15:0] \s5.s5_p2.buf_14 ;
  reg [15:0] \s5.s5_p2.buf_15 ;
  reg [15:0] \s5.s5_p2.buf_8 ;
  reg [15:0] \s5.s5_p2.buf_9 ;
  wire [35:0] \s5.s5_p2.p10 ;
  wire [35:0] \s5.s5_p2.p11 ;
  wire [35:0] \s5.s5_p2.p8 ;
  wire [35:0] \s5.s5_p2.p9 ;
  wire [36:0] \s5.s5_p2.partial2 ;
  wire [16:0] \s5.s5_p2.s10 ;
  wire [16:0] \s5.s5_p2.s8 ;
  wire [16:0] \s5.s5_p2.s9 ;
  wire [37:0] \s5.sum ;
  wire [15:0] stage1_out;
  wire [15:0] stage2_out;
  wire [15:0] stage3_out;
  wire [15:0] stage4_out;
  wire [15:0] stage5_out;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.buf_12  <= 16'h0000;
    else
      \s5.buf_12  <= \s5.s5_p2.buf_11 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_13  <= 16'h0000;
    else
      \s5.s5_p2.buf_13  <= \s5.buf_12 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_14  <= 16'h0000;
    else
      \s5.s5_p2.buf_14  <= \s5.s5_p2.buf_13 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_15  <= 16'h0000;
    else
      \s5.s5_p2.buf_15  <= \s5.s5_p2.buf_14 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_16  <= 16'h0000;
    else
      \s5.s5_p1.buf_16  <= \s5.s5_p2.buf_15 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_17  <= 16'h0000;
    else
      \s5.s5_p1.buf_17  <= \s5.s5_p1.buf_16 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_18  <= 16'h0000;
    else
      \s5.s5_p1.buf_18  <= \s5.s5_p1.buf_17 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_19  <= 16'h0000;
    else
      \s5.s5_p1.buf_19  <= \s5.s5_p1.buf_18 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_20  <= 16'h0000;
    else
      \s5.s5_p0.buf_20  <= \s5.s5_p1.buf_19 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_21  <= 16'h0000;
    else
      \s5.s5_p0.buf_21  <= \s5.s5_p0.buf_20 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_22  <= 16'h0000;
    else
      \s5.s5_p0.buf_22  <= \s5.s5_p0.buf_21 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_23  <= 16'h0000;
    else
      \s5.s5_p0.buf_23  <= \s5.s5_p0.buf_22 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_0  <= 16'h0000;
    else
      \s4.buf_0  <= \s3.sum_3 [23:8];
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_1  <= 16'h0000;
    else
      \s4.buf_1  <= \s4.buf_0 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_2  <= 16'h0000;
    else
      \s4.buf_2  <= \s4.buf_1 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_3  <= 16'h0000;
    else
      \s4.buf_3  <= \s4.buf_2 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_4  <= 16'h0000;
    else
      \s4.buf_4  <= \s4.buf_3 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_5  <= 16'h0000;
    else
      \s4.buf_5  <= \s4.buf_4 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_6  <= 16'h0000;
    else
      \s4.buf_6  <= \s4.buf_5 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_7  <= 16'h0000;
    else
      \s4.buf_7  <= \s4.buf_6 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_8  <= 16'h0000;
    else
      \s4.buf_8  <= \s4.buf_7 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_9  <= 16'h0000;
    else
      \s4.buf_9  <= \s4.buf_8 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s4.buf_10  <= 16'h0000;
    else
      \s4.buf_10  <= \s4.buf_9 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_0  <= 16'h0000;
    else
      \s3.buf_0  <= \s2.sum_3 [23:8];
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_1  <= 16'h0000;
    else
      \s3.buf_1  <= \s3.buf_0 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_2  <= 16'h0000;
    else
      \s3.buf_2  <= \s3.buf_1 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_3  <= 16'h0000;
    else
      \s3.buf_3  <= \s3.buf_2 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_4  <= 16'h0000;
    else
      \s3.buf_4  <= \s3.buf_3 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_5  <= 16'h0000;
    else
      \s3.buf_5  <= \s3.buf_4 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s3.buf_6  <= 16'h0000;
    else
      \s3.buf_6  <= \s3.buf_5 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_0  <= 16'h0000;
    else
      \s2.buf_0  <= \s1.sum_3 [23:8];
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_1  <= 16'h0000;
    else
      \s2.buf_1  <= \s2.buf_0 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_2  <= 16'h0000;
    else
      \s2.buf_2  <= \s2.buf_1 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_3  <= 16'h0000;
    else
      \s2.buf_3  <= \s2.buf_2 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_4  <= 16'h0000;
    else
      \s2.buf_4  <= \s2.buf_3 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_5  <= 16'h0000;
    else
      \s2.buf_5  <= \s2.buf_4 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s2.buf_6  <= 16'h0000;
    else
      \s2.buf_6  <= \s2.buf_5 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_0  <= 16'h0000;
    else
      \s1.buf_0  <= data_in;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_1  <= 16'h0000;
    else
      \s1.buf_1  <= \s1.buf_0 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_2  <= 16'h0000;
    else
      \s1.buf_2  <= \s1.buf_1 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_3  <= 16'h0000;
    else
      \s1.buf_3  <= \s1.buf_2 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_4  <= 16'h0000;
    else
      \s1.buf_4  <= \s1.buf_3 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_5  <= 16'h0000;
    else
      \s1.buf_5  <= \s1.buf_4 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s1.buf_6  <= 16'h0000;
    else
      \s1.buf_6  <= \s1.buf_5 ;
  always @(posedge clk or posedge rst)
    if (rst)
      data_out <= 16'h0000;
    else
      data_out <= \s5.sum [23:8];
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_0  <= 16'h0000;
    else
      \s5.s5_p0.buf_0  <= \s4.sum_5 [23:8];
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_1  <= 16'h0000;
    else
      \s5.s5_p0.buf_1  <= \s5.s5_p0.buf_0 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_2  <= 16'h0000;
    else
      \s5.s5_p0.buf_2  <= \s5.s5_p0.buf_1 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p0.buf_3  <= 16'h0000;
    else
      \s5.s5_p0.buf_3  <= \s5.s5_p0.buf_2 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_4  <= 16'h0000;
    else
      \s5.s5_p1.buf_4  <= \s5.s5_p0.buf_3 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_5  <= 16'h0000;
    else
      \s5.s5_p1.buf_5  <= \s5.s5_p1.buf_4 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_6  <= 16'h0000;
    else
      \s5.s5_p1.buf_6  <= \s5.s5_p1.buf_5 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p1.buf_7  <= 16'h0000;
    else
      \s5.s5_p1.buf_7  <= \s5.s5_p1.buf_6 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_8  <= 16'h0000;
    else
      \s5.s5_p2.buf_8  <= \s5.s5_p1.buf_7 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_9  <= 16'h0000;
    else
      \s5.s5_p2.buf_9  <= \s5.s5_p2.buf_8 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_10  <= 16'h0000;
    else
      \s5.s5_p2.buf_10  <= \s5.s5_p2.buf_9 ;
  always @(posedge clk or posedge rst)
    if (rst)
      \s5.s5_p2.buf_11  <= 16'h0000;
    else
      \s5.s5_p2.buf_11  <= \s5.s5_p2.buf_10 ;
  assign \s1.s0  = $signed(\s1.buf_0 ) + $signed(\s1.buf_6 );
  assign \s1.s1  = $signed(\s1.buf_1 ) + $signed(\s1.buf_5 );
  assign \s1.s2  = $signed(\s1.buf_2 ) + $signed(\s1.buf_4 );
  assign \s1.sum_1  = $signed(\s1.p0 ) + $signed(\s1.p1 );
  assign \s1.sum_2  = $signed(\s1.sum_1 ) + $signed(\s1.p2 );
  assign \s1.sum_3  = $signed(\s1.sum_2 ) + $signed(\s1.p3 );
  assign \s1.p0  = $signed({ \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0 [16], \s1.s0  }) * $signed(32'd109);
  assign \s1.p1  = $signed({ \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1 [16], \s1.s1  }) * $signed(36'hfffffffa0);
  assign \s1.p2  = $signed({ \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2 [16], \s1.s2  }) * $signed(32'd149);
  assign \s1.p3  = $signed({ \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3 [15], \s1.buf_3  }) * $signed(36'hfffffff06);
  assign \s2.s0  = $signed(\s2.buf_0 ) + $signed(\s2.buf_6 );
  assign \s2.s1  = $signed(\s2.buf_1 ) + $signed(\s2.buf_5 );
  assign \s2.s2  = $signed(\s2.buf_2 ) + $signed(\s2.buf_4 );
  assign \s2.sum_1  = $signed(\s2.p0 ) + $signed(\s2.p1 );
  assign \s2.sum_2  = $signed(\s2.sum_1 ) + $signed(\s2.p2 );
  assign \s2.sum_3  = $signed(\s2.sum_2 ) + $signed(\s2.p3 );
  assign \s2.p0  = $signed({ \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0 [16], \s2.s0  }) * $signed(32'd130);
  assign \s2.p1  = $signed({ \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1 [16], \s2.s1  }) * $signed(32'd191);
  assign \s2.p2  = $signed({ \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2 [16], \s2.s2  }) * $signed(32'd30);
  assign \s2.p3  = $signed({ \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3 [15], \s2.buf_3  }) * $signed(36'hfffffff75);
  assign \s3.s0  = $signed(\s3.buf_0 ) + $signed(\s3.buf_6 );
  assign \s3.s1  = $signed(\s3.buf_1 ) + $signed(\s3.buf_5 );
  assign \s3.s2  = $signed(\s3.buf_2 ) + $signed(\s3.buf_4 );
  assign \s3.sum_1  = $signed(\s3.p0 ) + $signed(\s3.p1 );
  assign \s3.sum_2  = $signed(\s3.sum_1 ) + $signed(\s3.p2 );
  assign \s3.sum_3  = $signed(\s3.sum_2 ) + $signed(\s3.p3 );
  assign \s3.p0  = $signed({ \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0 [16], \s3.s0  }) * $signed(32'd88);
  assign \s3.p1  = $signed({ \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1 [16], \s3.s1  }) * $signed(32'd71);
  assign \s3.p2  = $signed({ \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2 [16], \s3.s2  }) * $signed(32'd230);
  assign \s3.p3  = $signed({ \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3 [15], \s3.buf_3  }) * $signed(32'd123);
  assign \s4.s0  = $signed(\s4.buf_0 ) + $signed(\s4.buf_10 );
  assign \s4.s1  = $signed(\s4.buf_1 ) + $signed(\s4.buf_9 );
  assign \s4.s2  = $signed(\s4.buf_2 ) + $signed(\s4.buf_8 );
  assign \s4.s3  = $signed(\s4.buf_3 ) + $signed(\s4.buf_7 );
  assign \s4.s4  = $signed(\s4.buf_4 ) + $signed(\s4.buf_6 );
  assign \s4.sum_1  = $signed(\s4.p0 ) + $signed(\s4.p1 );
  assign \s4.sum_2  = $signed(\s4.sum_1 ) + $signed(\s4.p2 );
  assign \s4.sum_3  = $signed(\s4.sum_2 ) + $signed(\s4.p3 );
  assign \s4.sum_4  = $signed(\s4.sum_3 ) + $signed(\s4.p4 );
  assign \s4.sum_5  = $signed(\s4.sum_4 ) + $signed(\s4.p5 );
  assign \s4.p0  = $signed({ \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0 [16], \s4.s0  }) * $signed(36'hfffffffbf);
  assign \s4.p1  = $signed({ \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1 [16], \s4.s1  }) * $signed(32'd42);
  assign \s4.p2  = $signed({ \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2 [16], \s4.s2  }) * $signed(32'd26);
  assign \s4.p3  = $signed({ \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3 [16], \s4.s3  }) * $signed(32'd95);
  assign \s4.p4  = $signed({ \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4 [16], \s4.s4  }) * $signed(36'hfffffffda);
  assign \s4.p5  = $signed({ \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5 [15], \s4.buf_5  }) * $signed(36'hfffffff0b);
  assign _000_ = $signed(\s5.s5_p0.partial0 ) + $signed(\s5.s5_p1.partial1 );
  assign \s5.sum  = $signed(_000_) + $signed(\s5.s5_p2.partial2 );
  assign \s5.s5_p0.s0  = $signed(\s5.s5_p0.buf_0 ) + $signed(\s5.s5_p0.buf_23 );
  assign \s5.s5_p0.s1  = $signed(\s5.s5_p0.buf_1 ) + $signed(\s5.s5_p0.buf_22 );
  assign \s5.s5_p0.s2  = $signed(\s5.s5_p0.buf_2 ) + $signed(\s5.s5_p0.buf_21 );
  assign \s5.s5_p0.s3  = $signed(\s5.s5_p0.buf_3 ) + $signed(\s5.s5_p0.buf_20 );
  assign _001_ = $signed(\s5.s5_p0.p0 ) + $signed(\s5.s5_p0.p1 );
  assign _002_ = $signed(_001_) + $signed(\s5.s5_p0.p2 );
  assign \s5.s5_p0.partial0  = $signed(_002_) + $signed(\s5.s5_p0.p3 );
  assign \s5.s5_p0.p0  = $signed({ \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0 [16], \s5.s5_p0.s0  }) * $signed(32'd79);
  assign \s5.s5_p0.p1  = $signed({ \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1 [16], \s5.s5_p0.s1  }) * $signed(32'd28);
  assign \s5.s5_p0.p2  = $signed({ \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2 [16], \s5.s5_p0.s2  }) * $signed(36'hfffffff70);
  assign \s5.s5_p0.p3  = $signed({ \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3 [16], \s5.s5_p0.s3  }) * $signed(32'd37);
  assign \s5.s5_p1.s4  = $signed(\s5.s5_p1.buf_4 ) + $signed(\s5.s5_p1.buf_19 );
  assign \s5.s5_p1.s5  = $signed(\s5.s5_p1.buf_5 ) + $signed(\s5.s5_p1.buf_18 );
  assign \s5.s5_p1.s6  = $signed(\s5.s5_p1.buf_6 ) + $signed(\s5.s5_p1.buf_17 );
  assign \s5.s5_p1.s7  = $signed(\s5.s5_p1.buf_7 ) + $signed(\s5.s5_p1.buf_16 );
  assign _003_ = $signed(\s5.s5_p1.p4 ) + $signed(\s5.s5_p1.p5 );
  assign _004_ = $signed(_003_) + $signed(\s5.s5_p1.p6 );
  assign \s5.s5_p1.partial1  = $signed(_004_) + $signed(\s5.s5_p1.p7 );
  assign \s5.s5_p1.p4  = $signed({ \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4 [16], \s5.s5_p1.s4  }) * $signed(32'd78);
  assign \s5.s5_p1.p5  = $signed({ \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5 [16], \s5.s5_p1.s5  }) * $signed(32'd248);
  assign \s5.s5_p1.p6  = $signed({ \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6 [16], \s5.s5_p1.s6  }) * $signed(36'hfffffffdf);
  assign \s5.s5_p1.p7  = $signed({ \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7 [16], \s5.s5_p1.s7  }) * $signed(32'd71);
  assign \s5.s5_p2.s8  = $signed(\s5.s5_p2.buf_8 ) + $signed(\s5.s5_p2.buf_15 );
  assign \s5.s5_p2.s9  = $signed(\s5.s5_p2.buf_9 ) + $signed(\s5.s5_p2.buf_14 );
  assign \s5.s5_p2.s10  = $signed(\s5.s5_p2.buf_10 ) + $signed(\s5.s5_p2.buf_13 );
  assign _005_ = $signed(\s5.s5_p2.p8 ) + $signed(\s5.s5_p2.p9 );
  assign _006_ = $signed(_005_) + $signed(\s5.s5_p2.p10 );
  assign \s5.s5_p2.partial2  = $signed(_006_) + $signed(\s5.s5_p2.p11 );
  assign \s5.s5_p2.p8  = $signed({ \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8 [16], \s5.s5_p2.s8  }) * $signed(32'd79);
  assign \s5.s5_p2.p9  = $signed({ \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9 [16], \s5.s5_p2.s9  }) * $signed(32'd28);
  assign \s5.s5_p2.p10  = $signed({ \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10 [16], \s5.s5_p2.s10  }) * $signed(36'hfffffff70);
  assign \s5.s5_p2.p11  = $signed({ \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11 [15], \s5.s5_p2.buf_11  }) * $signed(32'd37);
  assign \buf1[0]  = \s1.buf_0 ;
  assign \buf1[1]  = \s1.buf_1 ;
  assign \buf1[2]  = \s1.buf_2 ;
  assign \buf1[3]  = \s1.buf_3 ;
  assign \buf1[4]  = \s1.buf_4 ;
  assign \buf1[5]  = \s1.buf_5 ;
  assign \buf1[6]  = \s1.buf_6 ;
  assign \buf2[0]  = \s2.buf_0 ;
  assign \buf2[1]  = \s2.buf_1 ;
  assign \buf2[2]  = \s2.buf_2 ;
  assign \buf2[3]  = \s2.buf_3 ;
  assign \buf2[4]  = \s2.buf_4 ;
  assign \buf2[5]  = \s2.buf_5 ;
  assign \buf2[6]  = \s2.buf_6 ;
  assign \buf3[0]  = \s3.buf_0 ;
  assign \buf3[1]  = \s3.buf_1 ;
  assign \buf3[2]  = \s3.buf_2 ;
  assign \buf3[3]  = \s3.buf_3 ;
  assign \buf3[4]  = \s3.buf_4 ;
  assign \buf3[5]  = \s3.buf_5 ;
  assign \buf3[6]  = \s3.buf_6 ;
  assign \buf4[0]  = \s4.buf_0 ;
  assign \buf4[10]  = \s4.buf_10 ;
  assign \buf4[1]  = \s4.buf_1 ;
  assign \buf4[2]  = \s4.buf_2 ;
  assign \buf4[3]  = \s4.buf_3 ;
  assign \buf4[4]  = \s4.buf_4 ;
  assign \buf4[5]  = \s4.buf_5 ;
  assign \buf4[6]  = \s4.buf_6 ;
  assign \buf4[7]  = \s4.buf_7 ;
  assign \buf4[8]  = \s4.buf_8 ;
  assign \buf4[9]  = \s4.buf_9 ;
  assign \buf5[0]  = \s5.s5_p0.buf_0 ;
  assign \buf5[10]  = \s5.s5_p2.buf_10 ;
  assign \buf5[11]  = \s5.s5_p2.buf_11 ;
  assign \buf5[12]  = \s5.buf_12 ;
  assign \buf5[13]  = \s5.s5_p2.buf_13 ;
  assign \buf5[14]  = \s5.s5_p2.buf_14 ;
  assign \buf5[15]  = \s5.s5_p2.buf_15 ;
  assign \buf5[16]  = \s5.s5_p1.buf_16 ;
  assign \buf5[17]  = \s5.s5_p1.buf_17 ;
  assign \buf5[18]  = \s5.s5_p1.buf_18 ;
  assign \buf5[19]  = \s5.s5_p1.buf_19 ;
  assign \buf5[1]  = \s5.s5_p0.buf_1 ;
  assign \buf5[20]  = \s5.s5_p0.buf_20 ;
  assign \buf5[21]  = \s5.s5_p0.buf_21 ;
  assign \buf5[22]  = \s5.s5_p0.buf_22 ;
  assign \buf5[23]  = \s5.s5_p0.buf_23 ;
  assign \buf5[2]  = \s5.s5_p0.buf_2 ;
  assign \buf5[3]  = \s5.s5_p0.buf_3 ;
  assign \buf5[4]  = \s5.s5_p1.buf_4 ;
  assign \buf5[5]  = \s5.s5_p1.buf_5 ;
  assign \buf5[6]  = \s5.s5_p1.buf_6 ;
  assign \buf5[7]  = \s5.s5_p1.buf_7 ;
  assign \buf5[8]  = \s5.s5_p2.buf_8 ;
  assign \buf5[9]  = \s5.s5_p2.buf_9 ;
  assign \s1.out  = \s1.sum_3 [23:8];
  assign \s2.out  = \s2.sum_3 [23:8];
  assign \s3.out  = \s3.sum_3 [23:8];
  assign \s4.out  = \s4.sum_5 [23:8];
  assign \s5.buf_0  = \s5.s5_p0.buf_0 ;
  assign \s5.buf_1  = \s5.s5_p0.buf_1 ;
  assign \s5.buf_10  = \s5.s5_p2.buf_10 ;
  assign \s5.buf_11  = \s5.s5_p2.buf_11 ;
  assign \s5.buf_13  = \s5.s5_p2.buf_13 ;
  assign \s5.buf_14  = \s5.s5_p2.buf_14 ;
  assign \s5.buf_15  = \s5.s5_p2.buf_15 ;
  assign \s5.buf_16  = \s5.s5_p1.buf_16 ;
  assign \s5.buf_17  = \s5.s5_p1.buf_17 ;
  assign \s5.buf_18  = \s5.s5_p1.buf_18 ;
  assign \s5.buf_19  = \s5.s5_p1.buf_19 ;
  assign \s5.buf_2  = \s5.s5_p0.buf_2 ;
  assign \s5.buf_20  = \s5.s5_p0.buf_20 ;
  assign \s5.buf_21  = \s5.s5_p0.buf_21 ;
  assign \s5.buf_22  = \s5.s5_p0.buf_22 ;
  assign \s5.buf_23  = \s5.s5_p0.buf_23 ;
  assign \s5.buf_3  = \s5.s5_p0.buf_3 ;
  assign \s5.buf_4  = \s5.s5_p1.buf_4 ;
  assign \s5.buf_5  = \s5.s5_p1.buf_5 ;
  assign \s5.buf_6  = \s5.s5_p1.buf_6 ;
  assign \s5.buf_7  = \s5.s5_p1.buf_7 ;
  assign \s5.buf_8  = \s5.s5_p2.buf_8 ;
  assign \s5.buf_9  = \s5.s5_p2.buf_9 ;
  assign \s5.out  = \s5.sum [23:8];
  assign \s5.partial0  = \s5.s5_p0.partial0 ;
  assign \s5.partial1  = \s5.s5_p1.partial1 ;
  assign \s5.partial2  = \s5.s5_p2.partial2 ;
  assign stage1_out = \s1.sum_3 [23:8];
  assign stage2_out = \s2.sum_3 [23:8];
  assign stage3_out = \s3.sum_3 [23:8];
  assign stage4_out = \s4.sum_5 [23:8];
  assign stage5_out = \s5.sum [23:8];
endmodule
